#!/bin/bash

#
# Filename:       parse-iommu-devices
# Description:    Bash script to parse, sort, and display hardware devices by
#                 selected IOMMU group, and return the device drivers and
#                 hardware IDs as output.
# Author(s):      Alex Portell <github.com/portellam>
# Maintainer(s):  Alex Portell <github.com/portellam>
# Version:        1.0.2
#

# set -o xtrace  # uncomment to debug.

#
# params
#
  declare -g SCRIPT_FILE="$( basename "${0}" )"
  declare -g SCRIPT_VERSION="1.0.2"
  declare -g SOURCE_PATH="/usr/local/bin/${SCRIPT_FILE}.d/"

#
# sources
#
  source \
    "${SOURCE_PATH}parse_src" \
    "${SOURCE_PATH}" \
    "${SCRIPT_FILE}" \
    "${SCRIPT_VERSION}"

#
# logic
#
  function main
  {
    set_tabspace_size
    # create_logfile
    # log "${0} ${@}"
    parse_many_arguments "${@}"

    if ! verify_groups; then
      return 1
    fi

    local -r message="Parsing hardware devices..."

    print_and_log_output "${message}"

    if ! parse_src_main; then
      print_and_log_output "${message} Failed."
      return 1
    fi

    print_and_log_output "${message} Successful.\n"
    print_groups_output
  }

main "$@"